apiVersion: apps/v1 # api version
kind: Deployment # type deployment
metadata:
  name: weather-app # Name of deployment
spec:
  replicas: 1
  selector: # manages the pod with label nginx-app
    matchLabels:
      app: nginx-app 
  template: # template is used for creating the pod with specified configuration
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-app # name of container
          image: nginx:latest # image used by pod 
          imagePullPolicy: Always # Always or IfNotPresent or Never
          ports:
            - containerPort: 80